package com.example.youtubeclone.model.videoId

data class Subtitle(
    val autoGenerated: Boolean = false,
    val code: String = "",
    val mimeType: String = "",
    val name: String = "",
    val url: String = ""
)